force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Cost__c.field-meta.xml
<CustomField>
    <fullName>Car_Cost__c</fullName>
    <label>Car Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/How_much_we_gain_lost__c.field-meta.xml
<CustomField>
    <fullName>How_much_we_gain_lost__c</fullName>
    <label>How much we gain/lost</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/jobs/CurrencyQueueable.cls
/*
* @author Dastan
*
* @date 2022-08-26
*
* @description Method to compare cost of the car when it was bought and when it was sold in AED 
*/
public with sharing class CurrencyQueueable implements Queueable, Database.AllowsCallouts {
    public static String targetCurrency = 'AED';
    public static String sourceCurrency = 'USD';

    private Set<Id> carIds;

    public CurrencyQueueable(List<Car__c> newCars, Map<Id, Car__c> oldMap) {
        this.carIds = new Set<Id>();
        for(Car__c c : newCars){
            if((c.Status__c == 'Done' && oldMap.get(c.Id).Status__c != 'Done') && c.Currency__c == 'AED'){
                carIds.add(c.Id);
            }
        }
    }
    public void execute(QueueableContext context){        
        String carBoughtDate;
        String carBoughtDay;
        String carBoughtMonth;
        String carBoughtYear;
        String carSoldDate;
        String amount;
        List<Car__c> carsToUpdate = new List<Car__c>();
        List<Car__c> soldCars = [SELECT Id, Car_Cost__c, Purchase_Date__c FROM Car__c WHERE Id =: carIds];
        for(Car__c c : soldCars){
            carBoughtDay = String.valueOf(c.Purchase_Date__c.day());
            if(!carBoughtDay.startsWith('0') && carBoughtDay.length() == 1){
                carBoughtDay = '0' + carBoughtDay;
            }
            carBoughtMonth = String.valueOf(c.Purchase_Date__c.month());
            if(!carBoughtMonth.startsWith('0') && carBoughtMonth.length() == 1){
                carBoughtMonth = '0' + carBoughtMonth;
            }
            carBoughtYear = String.valueOf(c.Purchase_Date__c.year());
            carBoughtDate = carBoughtYear + '-' +carBoughtMonth + '-' + carBoughtDay;
            carSoldDate = String.valueOf(Date.today()).removeEnd(' 00:00:00');
            amount = String.valueOf(c.Car_Cost__c);

            Double boughtCarAmount = CurrencyConverterIntegration.convertAmount(sourceCurrency, targetCurrency, amount, carBoughtDate);

            Double soldCarAmount = CurrencyConverterIntegration.convertAmount(sourceCurrency, targetCurrency, amount, carSoldDate);

            c.How_much_we_gain_lost__c = String.valueOf(soldCarAmount - boughtCarAmount);
            carsToUpdate.add(c);
        } 
        update carsToUpdate;
    }
}