force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Penalty_Cost__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Cost__c</fullName>
    <label>Penalty Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/jobs/StoragePenaltySchedulableTest.cls
@isTest
public class StoragePenaltySchedulableTest {
    
    @TestSetup
    static void setup (){
        List<Contact> conlist = new  List<Contact>();
        conlist.add(new Contact( LastName = 'Test  Contact 1', Email = 'bektur2130@gmail.com'));
        conlist.add(new Contact( LastName = 'Test  Contact 2', Email = 'bektur2130@gmail.com'));
        conlist.add(new Contact( LastName = 'Test  Contact 3', Email = 'bektur2130@gmail.com'));
        insert conlist;
        
        list<car__c> newcarlist=new list<car__c>();
        newcarlist.add(new car__c(name='test1', driver__c=conlist[0].ID, Storage_Cost__c=60,  Penalty_Cost__c = 60 ));
        newcarlist.add(new car__c(name='test2', driver__c=conlist[1].ID, Storage_Cost__c=70,  Penalty_Cost__c = 60 ));
        newcarlist.add(new car__c(name='test3', driver__c=conlist[2].ID, Storage_Cost__c=90,  Penalty_Cost__c = 60 ));
        insert newcarlist;
    }

    @isTest
    static void  testM(){
        Test.startTest();
        String cronExp = '0 0 9 * * ?';
        String jobId = System.Schedule('Storage Penalty Name', cronExp, new StoragePenaltySchedulable());        
        Test.stopTest();

        List<car__c> carList = [SELECT Id, Name, Storage_Cost__c, Penalty_Cost__c, Total_Cost__c FROM Car__c];
        System.assertEquals(120, carList[0].Storage_Cost__c + carList[0].Penalty_Cost__c);
    }
}