force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Penalty_Cost__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Cost__c</fullName>
    <label>Penalty Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/jobs/StoragePenaltySchedulable.cls
public class StoragePenaltySchedulable implements  Schedulable {
    
    public void execute (System.SchedulableContext sc) {
        List<Car__c> payList=[SELECT Id, Name, Storage_Cost__c, Penalty_Cost__c, Total_Cost__c FROM Car__c];
        List<Contact> conlist = [Select Id, Name, Email FROM Contact];
        
        Decimal allStorageCost= 0;
        Decimal allPenaltyCost= 0;
        
        for(Car__c n : paylist){
            if (n.Storage_Cost__c != null) {
                allStorageCost += n.Storage_Cost__c;
            }       
            if (n.Penalty_Cost__c != null) {
                allPenaltyCost += n.Penalty_Cost__c;
            }                                  
        }

        update payList;

        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{};
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new String[]{conlist[0].Email};
        message.plainTextBody = 'All Penalty Cost: '+ allPenaltyCost + '  All Storage Cost:  ' + allStorageCost;
        messages.add(message);  
        Messaging.sendEmail(messages);        
    }
}