force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/StorageChargeCheck.cls
public with sharing class StorageChargeCheck implements Database.Batchable<sObject>
{
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        //Get all purchased cars
        String query= 'Select id, Purchase_Date__c From Car__c Where Purchase_Date__c != null';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope)
    {
        Integer count = 0;
        //Iterate purchased cars
        for (Car__c c : (List<Car__c>)scope)
        {
            //Get purchased date
            Date purchasedDate = date.newinstance(c.Purchase_Date__c.year(), c.Purchase_Date__c.month(), c.Purchase_Date__c.day());
            
            //Get today's date
            Date today = System.today();
            
            //Calculate diffence between purchased date and today's date
            Integer numberDaysDue = purchasedDate.daysBetween(today);
            Integer storageCharge = 0;

            //Calculate storage charge
            if (numberDaysDue == 4)
            {
                storageCharge = 5;
            }
            else if (numberDaysDue == 5)
            {
                storageCharge = 10;
            }
            else if (numberDaysDue == 6) 
            {
                storageCharge = 15;
            }
            else if (numberDaysDue > 6)
            {
                storageCharge = numberDaysDue * 25;
            }

            //Edit storage cost field
            if (storageCharge > 0)
            {
                c.Storage_Cost__c = storageCharge;
                count++;
            }

        }//for loop

        //Update records
        if (count > 0)
        {
            update scope;
        }
    }

    public void finish(Database.BatchableContext bc)
    {}
}