force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Dismantled_Date__c.field-meta.xml
<CustomField>
    <fullName>Dismantled_Date__c</fullName>
    <label>Dismantled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Is_Dismantled__c.field-meta.xml
<CustomField>
    <fullName>Is_Dismantled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dismantled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars (Master)</relationshipLabel>
    <relationshipName>Cars1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/jobs/MonthlyEmployeeBonusPaymentsTest.cls
@isTest
public with sharing class MonthlyEmployeeBonusPaymentsTest {
    @isTest
    static void MonthlyEmployeeBonusPaymentsTest() {

        test.startTest ();
        MonthlyEmployeeBonusPayments testing = new MonthlyEmployeeBonusPayments();
        String chron = '0 0 10 1 *';        
        System.schedule('Test Sched', chron, testing);
        test.stopTest ();


        /*  BELOW CODE WAS SUPPOSED TO CREATE CARS AND TEST THE RESULT.
List<Car__c> dismantledCars = new List<Car__c>();
Contact tester = new Contact(Lastname='IamTester');
insert tester;
        for (Integer i; i<35; i++){
            dismantledCars.add(new Car__c(name='TestCar'+i, master__c=tester.id, Is_Dismantled__c=true,Dismantled_Date__c=Date.today()));
        }

test.startTest();
insert dismantledCars;
Test.stopTest();

Decimal bonuspayment=[select amount__c from Finance_Transaction__c where contact__c=tester.id AND type__c='Commission' limit 1];

System.assertEquals(350, bonuspayment);

    }
}
*/
    }
}