force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Is_Sold__c.field-meta.xml
<CustomField>
    <fullName>Is_Sold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/integrations/CarPartsIntegration.cls
@RestResource(urlMapping='/CarParts')
global class CarPartsIntegration {
    
    @HttpGet
    global static void getAvailableCarParts() {
        List<CarPartStructure> carParts = new List<CarPartStructure>();

        for(Car_Part__c carPart : [SELECT Id, Name, Car__r.Name, Price__c, Weight__c FROM Car_Part__c WHERE Is_Sold__c = FALSE]) {
            carParts.add(new CarPartStructure(carPart.Id, carPart.Name, carPart.Car__r.Name, carPart.Price__c, carPart.Weight__c));
        }

        RestResponse response = RestContext.response;
        
        response.statusCode = 200;
        response.responseBody = Blob.valueOf(JSON.serializePretty(carParts));
    }

    public class CarPartStructure {
        private String id;
        private String name;
        private String carName;
        private Decimal price;
        private Decimal weight;

        public CarPartStructure(String id, String name, String carName, Decimal price, Decimal weight) {
            this.id = id;
            this.name = name;
            this.carName = carName;
            this.price = price;
            this.weight = weight;
        }
    }
}