force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Penalty_Cost__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Cost__c</fullName>
    <label>Penalty Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/jobs/CheckIsPaidTest.cls
@isTest
public class CheckPenaltyTest {
    @testSetup  
    static void dataSetup(){
        Contact newContact = new Contact(LastName='ContactTest1');
        Contact newContact2 = new Contact(LastName='ContactTest2');
        insert newContact;
        insert newContact2;  
        
        List<Car__c> carList =new List<Car__c>();
        carList.add(new Car__c(Name = 'TEST1',Driver__c = newContact.Id,  Is_Paid__c=false,  Purchase_Date__c= System.today() + 11));
        carList.add(new Car__c(Name = 'TEST2',Driver__c = newContact2.Id, Is_Paid__c=false,  Purchase_Date__c= System.today() + 4));
        
        insert carList;
    }
    @isTest
    static void testM() {    
        Test.startTest();
        CheckIsPaid n = new CheckIsPaid(); 
        String cronExp = '0 0 9 * * ?';
        String jobId = System.Schedule('PenaltyAdd Schedule 3', cronExp, n);   
        
        Database.executeBatch(n, 10);     
        Test.stopTest();
        
        Car__c list1 = [SELECT Id, Name, Driver__c, Is_Paid__c, Purchase_Date__c, Penalty_Cost__c 
                        FROM Car__c where Name= 'TEST1'];
        Car__c list2 = [SELECT Id, Name, Driver__c, Is_Paid__c, Purchase_Date__c, Penalty_Cost__c 
                        FROM Car__c where Name= 'TEST2'];  
        
        system.assertEquals(300,list1.Penalty_Cost__c, 'Failed');
        system.assertEquals(50,list2.Penalty_Cost__c, 'Failed');    
        
    }     
}