force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Is_Export__c.field-meta.xml
<CustomField>
    <fullName>Is_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/service/ContainerServicerTest.cls
@isTest(SeeAllData=false)
private class ContainerServicerTest {
    
    @TestSetup
    static void setup(){
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        Contact con = new Contact(FirstName='Test', LastName='Contact');
        insert con;
        Car__c car = new Car__c(Name = 'Test Car', Driver__c = con.id, Is_Paid__c = false);
        insert car;
        Container__c container = new Container__c(Account__c = acc.id);
        insert container;
        Car_Part__c carPart = new Car_Part__c(Car__c = car.id, Container__c = container.id, Is_Export__c = true);
        insert carPart;
    }

    @isTest static void testReleaseContainer(){
        Container__c container = [Select id, Status__c From Container__c][0];
        container.Status__c = 'Release';

        Test.startTest();
        Database.SaveResult result = Database.update(container, false);
        Test.stopTest();

        System.assertEquals('We can\'t release containers with unpaid car parts!!!', result.getErrors()[0].getMessage());
    }
} 