force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/controllers/LwcPdfGeneratorForCarPartsControllerTest.cls
@isTest
public with sharing class LwcPdfGeneratorForCarPartsControllerTest {
    @TestSetup static void Setup(){
        Contact con = new Contact(
            LastName = 'test'
        );
        insert con;
        Car__c car = new Car__c(
            Name = 'Mercedes',
            Driver__c = con.Id
        );
        insert car;
        Car_Part__c cp = new Car_Part__c(
            Price__c = 100,
            Car__c = car.Id
        );
        insert cp;
    }
    @isTest
    public static void GetCarParsTest() {
        Car__c car = [SELECT Id FROM Car__c WHERE Name = 'Mercedes'];
        Car_Part__c carPart = [SELECT Id FROM Car_Part__c];
        List<Car_Part__c> existingCarParts = LwcPdfGeneratorForCarPartsController.getCarParts(car.Id);
        System.assertEquals(carPart.Id, existingCarParts[0].Id);
    }
}