force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Is_Picked_Up__c.field-meta.xml
<CustomField>
    <fullName>Is_Picked_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Picked Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/jobs/CarPickingCheckBatchTest.cls
@IsTest(SeeAllData=false)
private class CarPickingCheckBatchTest {

    @IsTest
    static void carPickingCheckBatchPositiveTest() {
        //given
        Contact driver = new Contact(LastName = 'Bob', Email = 'test.emai@driver.com');
        insert driver;
        insert new Car__c(Driver__c = driver.Id, Is_Paid__c = true, Purchase_Date__c = System.today().addDays(-10), Is_Picked_Up__c = false);

        //when
        Test.startTest();
        CarPickingCheckBatch batch = new CarPickingCheckBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();        
    }
}