force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/jobs/StorageChargeCheckTest.cls
@isTest
public class StorageChargeCheckTest 
{
    @testSetup
    static void setup() 
    {
        Contact c = new Contact(LastName = 'TestDriver');
        insert c;
        List<Car__c> cars = new List<Car__c>();

        // insert 5 cars with different purchased day.
        for (Integer i = 3; i < 8; i++) 
        {
            cars.add(new Car__c(Name = 'Car' + i, Driver__c = c.id, Purchase_Date__c = System.now().AddDays(i)));
        }

        insert cars;
    }

    @isTest static void test()
    {
        Database.executeBatch(new StorageChargeCheckBatch());

        List<Car__c> allCars = [Select id, Storage_Cost__c From Car__c];

        Set<Car__c> cars = new Set<Car__c>();

        for (Car__c car : allCars)
        {
            if (car.Storage_Cost__c == null)
            {
                cars.add(car);
            }
            else if (car.Storage_Cost__c == 5)
            {
                cars.add(car);
            }
            else if (car.Storage_Cost__c == 10)
            {
                cars.add(car);
            }
            else if (car.Storage_Cost__c == 15)
            {
                cars.add(car);
            }
            else if (car.Storage_Cost__c == 125)
            {
                cars.add(car);
            }
        }
        System.assertEquals(5, cars.size());
    }
}