force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Dismantled_Date__c.field-meta.xml
<CustomField>
    <fullName>Dismantled_Date__c</fullName>
    <label>Dismantled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Is_Dismantled__c.field-meta.xml
<CustomField>
    <fullName>Is_Dismantled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dismantled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars (Master)</relationshipLabel>
    <relationshipName>Cars1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/jobs/SevenCarsWeekSchedulableTest.cls
@isTest
public class SevenCarsWeekSchedulableTest {
    @isTest
    static void finTransTest() {

       
        //given
        
        List<Car__c> dismantledCars = new List<Car__c>();
        List<Car__c> dismantledCars2 = new List<Car__c>();
   
        //create contacts for above nad below treshold of 7 cars
        Contact mBelow = new Contact(Lastname='mBelow');
        Contact mAbove = new Contact(Lastname='mAbove');
        
        insert mBelow;
        insert mAbove;
   
        for (Integer i=1; i<3; i++){
          dismantledCars.add(new Car__c(name='car1'+i,driver__c=mBelow.id, master__c=mBelow.id, Is_Dismantled__c=true,Dismantled_Date__c=Date.today()-1));
        }
       insert dismantledCars;
        
        for (Integer i=1; i<9; i++){
            dismantledCars2.add(new Car__c(name='carA'+i,driver__c=mabove.id, master__c=mabove.id, Is_Dismantled__c=true,Dismantled_Date__c=Date.today()));
        }
        insert dismantledCars2;

        //when
             
        system.test.starttest();
        //SchedulableContext sc = null;
        //SevenCarsWeekSchedulable tst = new SevenCarsWeekSchedulable();
        //tst.execute(sc);

          
      
        SevenCarsWeekSchedulable s =new SevenCarsWeekSchedulable();
        s.execute(null) ;

        system.test.stopTest();

       


        //then
        
      Finance_Transaction__c fBelow  = [SELECT contact__c, amount__c FROM Finance_Transaction__c WHERE contact__c =: mBelow.id limit 1 ];
      Finance_Transaction__c fAbove  = [SELECT contact__c, amount__c FROM Finance_Transaction__c WHERE contact__c=:  mAbove.id limit 1];
       
     System.assertEquals(-200, fBelow.amount__C);
     System.assertEquals(fAbove.amount__C,200);
  
    }
}