force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Cost__c.field-meta.xml
<CustomField>
    <fullName>Car_Cost__c</fullName>
    <label>Car Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars (Master)</relationshipLabel>
    <relationshipName>Cars1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/jobs/CurrencyQueueableTest.cls
@isTest
public with sharing class CurrencyQueueableTest {
    @TestSetup
    static void makeData(){
        Datetime todayDate = DateTime.newInstance(2021, 1, 31, 7, 8, 16);
        Contact contact = new Contact(
            LastName = 'test',
            Position__c = 'Master'
        );
        insert contact;
        Car__c car = new Car__c(
            Name = 'Mercedes',
            Purchase_Date__c = todayDate,
            Driver__c = contact.Id,
            Master__c = contact.Id,
            Car_Cost__c = 20000,
            Currency__c = 'AED'
        );
        insert car;
        Car__c car1 = new Car__c(
            Name = 'Mercedes',
            Purchase_Date__c = todayDate,
            Driver__c = contact.Id,
            Master__c = contact.Id,
            Car_Cost__c = 20000,
            Currency__c = 'AED'
        );
        insert car1;
        
    }
    @isTest
    public static void CurrencyQueueableTest1 (){
        Map<Id, Car__c> idToOldCarsMap = new Map<Id, Car__c>();
        List<Car__c> carList = [SELECT Id, Status__c FROM Car__c];
        for(Car__c c : carList){
            idToOldCarsMap.put(c.Id, c);
            c.Status__c = 'Done';
        }
        update carList;

        Test.setMock(HttpCalloutMock.class, new CurrencyConverterIntegrationTest.CurrencyConverterIntegrationMock()); 

        // CurrencyQueueable updateJob = new CurrencyQueueable(carList, carsToUpdate);
        // System.engueueJob(updateJob);

        System.assertEquals(2, [SELECT COUNT() FROM Car__c WHERE Status__c = 'Done']);
    }
}