force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Is_Dismantled__c.field-meta.xml
<CustomField>
    <fullName>Is_Dismantled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dismantled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars (Master)</relationshipLabel>
    <relationshipName>Cars1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/LwcReportForMastersControllerTest.cls
/**
 * @author Dastan
 * @date 2022-08-23
 *
 * @description Test Class for LwcReportForMastersController Class
 */
@isTest
public with sharing class LwcReportForMastersControllerTest {
    @TestSetup
    static void makeData(){
        Contact contact = new Contact(
            LastName = 'test',
            Position__c = 'Master'
        );
        insert contact;
        Car__c car = new Car__c(
            Name = 'Mercedes',
            Driver__c = contact.Id,
            Master__c = contact.Id,
            Is_Dismantled__c = true
        );  
        insert car;
        Car_Part__c carPart1 = new Car_Part__c(
            Car__c = car.Id,
            Price__c = 100
        );
        insert carPart1;
        Car_Part__c carPart2 = new Car_Part__c(
            Car__c = car.Id,    
            Price__c = 200
        );
        insert carPart2;
        Car_Part__c carPart3 = new Car_Part__c(
            Car__c = car.Id,
            Price__c = 300
        );
        insert carPart3;
    }
    @isTest
    public static void getCarQuantityTest() {
        Contact contact = [SELECT Id FROM Contact WHERE LastName = 'test'];
        Decimal carsNumber = [SELECT COUNT() FROM Car__c WHERE Name = 'Mercedes'];
        Decimal existingCarsCount = LwcReportForMastersController.getCarQuantity(contact.Id);

        System.assertEquals(carsNumber, existingCarsCount);
    }
    @isTest
    public static void getRelatedCarPartsTest() {
        Contact contact = [SELECT Id FROM Contact WHERE LastName = 'test'];
        List<Car_Part__c> carPartList = [SELECT Id FROM Car_Part__c];
        List<LwcReportForMastersController.DataTableWrapper> wrapperList = LwcReportForMastersController.getRelatedCarParts(contact.Id);

        System.assertEquals(wrapperList.size(), 3);
    }   
}