force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Comission__c.field-meta.xml
<CustomField>
    <fullName>Comission__c</fullName>
    <label>Comission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinanceTransaction/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/services/FinanceTransactionService.cls
public with sharing class FinanceTransactionService {

    /**
     * Method update two fields in Cars object when in FinanceTransaction object chosen:
     *   Type 'Storage' -> 'Amount' from FinanTransaction add to field 'Storage Cost' in Cars object;
     *   Type 'Commissiom' -> 'Amount' from FinanTransaction add to field 'Commission' in Cars object;
     * @param CarList 
     * @author malika
     */

     public static void UpdateCostFieldsofCar(List<Finance_Transaction__c> NewList){
        List<Car__c> CarList = [SELECT Id, Name, Comission__c, Storage_Cost__c, 
                                (SELECT Type__c, Amount__c FROM Finance_Transactions1__r) 
                                FROM Car__c];
        List<Car__c> CarListNew = new List<Car__c>();
        for(Car__c Carn: CarList){
            for(Finance_Transaction__c Finn: Carn.Finance_Transactions1__r){
                if(Finn.Type__c=='Storage'){
                    Carn.Storage_Cost__c =  Carn.Storage_Cost__c + Finn.Amount__c;
                    CarListNew.add(Carn);
                }
                else if(Finn.Type__c=='Commission'){
                    Carn.Comission__c =  Carn.Comission__c + Finn.Amount__c ;
                    CarListNew.add(Carn);
                }
            }
        }
        update CarListNew;
    }
}