force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Dismantled_Date__c.field-meta.xml
<CustomField>
    <fullName>Dismantled_Date__c</fullName>
    <label>Dismantled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Is_Dismantled__c.field-meta.xml
<CustomField>
    <fullName>Is_Dismantled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dismantled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars (Master)</relationshipLabel>
    <relationshipName>Cars1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/jobs/SevenCarsWeekSchedulable.cls
    /**
     * Scheduable batch method to check if the master dismantled more or less than 7 cars a week and to add according finance transaction
     * 
     * 
     * @author MartinCapek
     */


public with sharing class SevenCarsWeekSchedulable implements  Schedulable {
    
public void execute (schedulablecontext ctx){
   
    //list of aggregated accounts by dismantled cars *LAST_N_DAYS:6* containstoday + 6 days 7 in total, needs to be scheduled on Sunday, not monday to cover the week
    List <aggregateResult> below7 = [SELECT master__c, COUNT (id) FROM car__c WHERE Is_Dismantled__c = true AND Dismantled_Date__c = LAST_N_DAYS:6 GROUP BY Master__c Having count (id) <7]; 
    List <aggregateResult> above7 = [SELECT master__c, COUNT (id) FROM car__c WHERE Is_Dismantled__c = true AND Dismantled_Date__c = LAST_N_DAYS:6  GROUP BY Master__c Having count (id)>7]; 
    
    //new empty list for transactions
    List <Finance_Transaction__c> financeList = new list <finance_transaction__c>();
    
    //loop throught the results to to create new transactions *(string)b7.get('master__c')* transforms master__c object in to the string usable as Id for contact 
    For (aggregateResult b7:below7){
        financeList.add(new Finance_Transaction__c  (Contact__c=(string)b7.get('master__c'), amount__C=-200,Type__c='Commission'));
    }
    For (aggregateResult a7:above7){
        financeList.add(new Finance_Transaction__c  (Contact__c=(string)a7.get('master__c'), amount__C=+200,Type__c='Commission'));
       
    }
    
    insert financeList;
    }
}