force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Is_Picked_Up__c.field-meta.xml
<CustomField>
    <fullName>Is_Picked_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Picked Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/jobs/StorageChargeCheckBatch.cls
public with sharing class StorageChargeCheckBatch implements Database.Batchable<sObject>{
   
    public Database.QueryLocator start(Database.BatchableContext bc){                
        return Database.getQueryLocator('SELECT id, Purchase_Date__c FROM Car__c WHERE Purchase_Date__c != null AND Is_Picked_Up__c = false');
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope){
        List<Car__c> carsToUpdate = new List<Car__c>();
        
        for (Car__c c : (List<Car__c>)scope){            
            Date purchasedDate = c.Purchase_Date__c.date();
            Date today = System.today();
            
            Integer numberDaysDue = purchasedDate.daysBetween(today);
            Decimal storageCharge = 0;

            if (numberDaysDue == 4){
                storageCharge = 5;
            } else if (numberDaysDue == 5){
                storageCharge = 10;
            } else if (numberDaysDue == 6){
                storageCharge = 15;
            } else if (numberDaysDue == 7){
                storageCharge = 25;
            } else if (numberDaysDue > 7){
                storageCharge = c.Storage_Cost__c + 25;
            }

            if (storageCharge > 0){
                c.Storage_Cost__c = storageCharge;
                carsToUpdate.add(c);
            }
        }
        update carsToUpdate;
    }

    public void finish(Database.BatchableContext bc){
    }
}