force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Is_Picked_Up__c.field-meta.xml
<CustomField>
    <fullName>Is_Picked_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Picked Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/jobs/CarPickingCheckBatch.cls
public class CarPickingCheckBatch implements Database.Batchable<Sobject>, Schedulable {
    
    public void execute(SchedulableContext  sc) {
        CarPickingCheckBatch batch = new CarPickingCheckBatch();
        Database.executeBatch(batch, 200);
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String condition = '(SELECT Driver__c FROM Car__c WHERE Is_Picked_Up__c = FALSE AND Is_Paid__c = TRUE AND Purchase_Date__c < LAST_N_DAYS:2 AND Purchase_Date__c != NULL)';
        String subquery = '(SELECT Name, Purchase_Date__c FROM Cars__r WHERE Purchase_Date__c != NULL)';
        
        return Database.getQueryLocator('SELECT FirstName, Email, ' + subquery + ' FROM Contact WHERE Id IN ' + condition);
     }    

    public void execute(Database.BatchableContext info, List<Contact> scope){     
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{};
        
        for(Contact driver : scope){             
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.toAddresses = new String[]{driver.Email};
            message.setSubject('Reminder for picking up car');
            message.plainTextBody = 'Hello ' + driver.FirstName +',\nyou are getting this message, because the following cars: \n\n';
            
            for(Car__c car : driver.Cars__r) {
                message.plainTextBody += 'Name: ' + car.Name + ' | Purchase date: ' + car.Purchase_Date__c + '\n';
            }   

            message.plainTextBody += '\nThis is kindly reminder, because we are getting penalties for storage in auction. \nKing regards,';
            messages.add(message);             
        }        
        Messaging.sendEmail(messages);  
    }     

    public void finish(Database.BatchableContext info){     
    } 
}