force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Is_Sold__c.field-meta.xml
<CustomField>
    <fullName>Is_Sold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Nose Cut</fullName>
            </value>
            <value>
                <fullName>Front Bumper</fullName>
            </value>
            <value>
                <fullName>Hood</fullName>
            </value>
            <value>
                <fullName>Half Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Car_Part__c.field-meta.xml
<CustomField>
    <fullName>Car_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Part</label>
    <referenceTo>Car_Part__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/CarPartService.cls
public with sharing class CarPartService {

   /**
     * Method to create Finance transaction record based on selling Car Part.
     * 
     * @param oldMap old Car Parts 
     * @param newMap new Car Parts
     * @author canselagasiyeva 
     */
    public static void handleSell(Map<Id, Car_Part__c> oldMap, Map<Id, Car_Part__c> newMap) {
        List<Finance_Transaction__c> newFinanceTransactionList = new List<Finance_Transaction__c>();
        for(Car_Part__c part : newMap.values()){
            if(part.Is_Sold__c && (oldMap == null || !oldMap.get(part.Id).Is_Sold__c)){
               newFinanceTransactionList.add(new Finance_Transaction__c(Amount__c = part.Price__c, Car_Part__c = part.Id, Car__c = part.Car__c, Type__c = FinanceTransactionService.SELL_TYPE));
            }    
        }
        insert newFinanceTransactionList;
    }
} 