force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Is_Sold__c.field-meta.xml
<CustomField>
    <fullName>Is_Sold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Nose Cut</fullName>
            </value>
            <value>
                <fullName>Front Bumper</fullName>
            </value>
            <value>
                <fullName>Hood</fullName>
            </value>
            <value>
                <fullName>Half Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/LwcCarSoldPartChartController.cls
public with sharing class LwcCarSoldPartChartController {
    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getStatistics(Id recordId) {
        Map<String, Integer> dataset = new Map<String, Integer>();
        for(AggregateResult record : [SELECT Type__c, COUNT(Id) Total FROM Car_Part__c WHERE is_Sold__c=true AND Car__c=:recordID GROUP BY Type__c]) {
            dataset.put((String) record.get('Type__c'), (Integer) record.get('Total'));
        }
        return dataset;  
    }
}