force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Penalty_Cost__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Cost__c</fullName>
    <label>Penalty Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/jobs/CheckPaymentBatch.cls
public class CheckPaymentBatch implements Database.Batchable<Sobject>, Schedulable {

    public void execute(SchedulableContext sc) {
        CheckPaymentBatch batch = new CheckPaymentBatch();
        Database.executeBatch(batch, 10);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Name, Is_Paid__c, Penalty_Cost__c, Purchase_Date__c FROM Car__c where Is_Paid__c=FALSE');
    }

    public void execute(Database.BatchableContext bc, List<Car__c> records) {
        List<Car__c> newCarList = new List<Car__c>();
        for (Car__c c : records) {
            if (System.today().daysBetween(Date.valueOf(c.Purchase_Date__c)) > 10) {
                c.Penalty_Cost__c = 300;
                newCarList.add(c);
            } else if (System.today().daysBetween(Date.valueOf(c.Purchase_Date__c)) > 3) {
                c.Penalty_Cost__c = 50;
                newCarList.add(c);
            }
        }
        update newCarList;
    }

    public void finish(Database.BatchableContext bc) {
    }
}