force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Comission__c.field-meta.xml
<CustomField>
    <fullName>Comission__c</fullName>
    <label>Comission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Storage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Storage_Cost__c</fullName>
    <label>Storage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Nose Cut</fullName>
            </value>
            <value>
                <fullName>Front Bumper</fullName>
            </value>
            <value>
                <fullName>Hood</fullName>
            </value>
            <value>
                <fullName>Half Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Car_Part__c.field-meta.xml
<CustomField>
    <fullName>Car_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Part</label>
    <referenceTo>Car_Part__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinanceTransaction/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceTransaction/fields/Car_Part__c.field-meta.xml
<CustomField>
    <fullName>Car_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Part</label>
    <referenceTo>Car_Part__c</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/service/FinanceTransactionService.cls
public with sharing class FinanceTransactionService {
    public static final String SELL_TYPE = 'Sell';
    
    /**
     * Method update two fields in Cars object when in FinanceTransaction object chosen:
     *   Type 'Storage' -> 'Amount' from FinanTransaction add to field 'Storage Cost' in Cars object;
     *   Type 'Commissiom' -> 'Amount' from FinanTransaction add to field 'Commission' in Cars object;
     * @param CarList 
     * @author malika
     */
     public static void UpdateCostFieldsofCar(List<Finance_Transaction__c> NewList){
        List<Car__c> CarList = [SELECT Id, Name, Comission__c, Storage_Cost__c, 
                                (SELECT Type__c, Amount__c FROM Finance_Transactions1__r) 
                                FROM Car__c];
        List<Car__c> CarListNew = new List<Car__c>();
        for(Car__c Carn: CarList){
            for(Finance_Transaction__c Finn: Carn.Finance_Transactions1__r){
                if(Finn.Type__c=='Storage'){
                    Carn.Storage_Cost__c =  Carn.Storage_Cost__c + Finn.Amount__c;
                    CarListNew.add(Carn);
                }
                else if(Finn.Type__c=='Commission'){
                    Carn.Comission__c =  Carn.Comission__c + Finn.Amount__c ;
                    CarListNew.add(Carn);
                }
            }
        }
        update CarListNew;
    }
    
    /**
     * When payment for sold Car Parts comes, method adds amount to revenue amount on Car.
     *     
     * @param newList new inserted Finance_Transaction__c record
     * @author canselagasiyeva 
     */
    public static void addRevenue(List<Finance_Transaction__c> newList) {   
        Set<Id> carIds = new Set<Id>();
        
        for(Finance_Transaction__c payment : newList) {
            carIds.add(payment.Car__c);
        } 
        
        Map<Id, Car__c> mapCars = new Map<Id, Car__c>([SELECT Id, Revenue__c FROM Car__c WHERE Id IN :carIds]);
        for(Finance_Transaction__c payment : newList) {
            if (payment.Type__c == SELL_TYPE && payment.Car_Part__c != null && payment.Car__c != null) {                                            
                if(mapCars.get(payment.Car__c).Revenue__c == null) {
                    mapCars.get(payment.Car__c).Revenue__c = payment.Amount__c;
                } else {
                    mapCars.get(payment.Car__c).Revenue__c += payment.Amount__c;
                }
            }
        }
        update mapCars.values();
    }
}