force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/Car_Part__c.object-meta.xml
<CustomObject>
    <label>Car Part</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Part__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Part__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Car Parts</relationshipLabel>
    <relationshipName>Car_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/ContainerService.cls
public with sharing class ContainerService {

    public static void checkPayments(Set<Container__c> updatedContainers) {
        /*Since Trigger.new may contain more than 1 object, geting all car parts of updated containers where parent car
        object's isPaid field equals to False*/
        List<Car_Part__c> allCarParts = [Select id, Container__c, Car__c From Car_Part__c WHERE Car__r.Is_Paid__c = False AND Container__c in :updatedContainers];

        //Map to storage sorted car parts by containers
        Map<Container__c, List<Car_Part__c>> sortedCarParts = new Map<Container__c, List<Car_Part__c>>();
        
        //Set To storage updated containers
        Set<Container__c> releasedContainers = new Set<Container__c>();

        //Sorting car parts by released containers
        for (Container__c c : updatedContainers){
            if (c.Status__c == 'Release'){
                List<Car_Part__c> carParts = new List<Car_Part__c>();

                for (Integer i = 0; i < allCarParts.size(); i++){
                    if (allCarParts[i].Container__c == c.id){
                        carParts.add(allCarParts[i]);
                        allCarParts.remove(i);
                    }
                }

                sortedCarParts.put(c, carParts);
                releasedContainers.add(c);
            }
        }

        //If container has more than 1 unpaid car part, prevents to update
        for (Container__c c : releasedContainers){
            if (sortedCarParts.get(c).size() > 0){
                c.addError('We can\'t release containers with unpaid car parts!!!');
            }
        }
    }
}