force-app/main/default/objects/Finance_Transaction__c/Finance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Finance Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Transactions</relationshipLabel>
    <relationshipName>Finance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selector/FinanceTransactionSelector.cls
public class FinanceTransactionSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {            
            Finance_Transaction__c.Id,
            Finance_Transaction__c.Account__c,
            Finance_Transaction__c.Name
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Finance_Transaction__c.SObjectType;
    }

    public List<Finance_Transaction__c> selectById(Set<Id> idSet) {
        return (List<Finance_Transaction__c>) selectSObjectsById(idSet);
    }
}